In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [4]:
## Load the dataset
data=pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
## Preprocess the data
### Drop irrelevant columns
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [6]:
## Encode categorical variables
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0

In [7]:
## Onehot encode 'Geography
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo=OneHotEncoder()
geo_encoder=onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoder

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [8]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [9]:
geo_encoded_df=pd.DataFrame(geo_encoder,columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [10]:
## Combine one hot encoder columns with the original data
data=pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [11]:
## Save the encoders and sscaler
with open('label_encoder_gender1.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo1.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo,file)

In [12]:
## DiVide the dataset into indepent and dependent features
X=data.drop('Exited',axis=1)
y=data['Exited']

## Split the data in training and tetsing sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

## Scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [13]:
with open('scaler1.pkl','wb') as file:
    pickle.dump(scaler,file)

###ANN IMPLEMENTAION

In [1]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [20]:
(X_train.shape[1],)

(12,)

In [21]:
## Build Our ANN Model
model=Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)), ## HL1 Connected wwith input layer
    Dense(32,activation='relu'), ## HL2
    Dense(1,activation='sigmoid')  ## output layer
]
)

In [22]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [23]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy()
loss

In [24]:
model.compile(optimizer=opt,loss="binary_crossentropy",metrics=['accuracy'])

In [25]:
# Set up the Tensorboard
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard

log_dir="logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [26]:
## Set up Early Stopping
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [30]:
### Train the model
history=model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3439 - accuracy: 0.8611 - val_loss: 0.3397 - val_accuracy: 0.8575
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3367 - accuracy: 0.8608 - val_loss: 0.3545 - val_accuracy: 0.8535
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3360 - accuracy: 0.8621 - val_loss: 0.3417 - val_accuracy: 0.8540
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3342 - accuracy: 0.8630 - val_loss: 0.3495 - val_accuracy: 0.8635
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3320 - accuracy: 0.8637 - val_loss: 0.3504 - val_accuracy: 0.8570
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3282 - accuracy: 0.8651 - val_loss: 0.3469 - val_accuracy: 0.8575
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3249 - accuracy: 0.8690 - val_loss: 0.3373 - val_accuracy: 0.8600
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3260 - accuracy: 0.8654 - val_loss: 0.3428 - val_accuracy: 0.8575
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3222 - accuracy: 0.8673 - val_loss: 0.3464 - val_accuracy: 0.8590
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3219 - accuracy: 0.8689 - val_loss: 0.3457 - val_accuracy: 0.8590
Epoch 11/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3197 - accuracy: 0.8698 - val_loss: 0.3406 - val_accuracy: 0.8605
Epoch 12/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3185 - accuracy: 0.8684 - val_loss: 0.3430 - val_accuracy: 0.8585
Epoch 13/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3151 - accuracy: 0.8696 - val_loss: 0.3609 - val_accuracy: 0.8545
Epoch 14/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3162 - accuracy: 0.8692 - val_loss: 0.3481 - val_accuracy: 0.8600
Epoch 15/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3095 - accuracy: 0.8735 - val_loss: 0.3499 - val_accuracy: 0.8580
Epoch 16/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3095 - accuracy: 0.8735 - val_loss: 0.3661 - val_accuracy: 0.8565
Epoch 17/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3088 - accuracy: 0.8744 - val_loss: 0.3638 - val_accuracy: 0.8580

In [31]:
model.save('mymodel.h5')

In [5]:
## Load Tensorboard Extension

%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [6]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 60440), started 0:00:48 ago. (Use '!kill 60440' to kill it.)

In [7]:
!kill 60440

In [8]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [9]:
### Load the trained model, scaler pickle,onehot
model=load_model('mymodel.h5')

## load the encoder and scaler
with open('onehot_encoder_geo1.pkl','rb') as file:
    label_encoder_geo=pickle.load(file)

with open('label_encoder_gender1.pkl', 'rb') as file:
    label_encoder_gender = pickle.load(file)

with open('scaler1.pkl', 'rb') as file:
    scaler = pickle.load(file)

In [11]:
# Example input data
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [12]:
# One-hot encode 'Geography'
geo_encoded = label_encoder_geo.transform([[input_data['Geography']]]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=label_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

/home/npci-admin/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [13]:
input_df=pd.DataFrame([input_data])
input_df

   CreditScore Geography Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          600    France   Male  ...          1               1            50000

[1 rows x 10 columns]

In [14]:
input_df['Gender']=label_encoder_gender.transform(input_df['Gender'])
input_df

   CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          600    France       1  ...          1               1            50000

[1 rows x 10 columns]

In [15]:
## concatination one hot encoded 
input_df=pd.concat([input_df.drop("Geography",axis=1),geo_encoded_df],axis=1)
input_df

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          600       1  ...                0.0              0.0

[1 rows x 12 columns]

In [16]:
## Scaling the input data
input_scaled=scaler.transform(input_df)
input_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [17]:
prediction=model.predict(input_scaled)
prediction

1/1 [==============================] - 0s 86ms/step

array([[0.04028279]], dtype=float32)

In [18]:
prediction_proba = prediction[0][0]

In [19]:
if prediction_proba > 0.5:
    print('The customer is likely to churn.')
else:
    print('The customer is not likely to churn.')

The customer is not likely to churn.