In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

/home/npci-admin/anaconda3/lib/python3.9/site-packages/pandas/core/computation/expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
/home/npci-admin/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.4' currently installed).
  from pandas.core import (

In [2]:
data=pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
# Preprocess the data
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [4]:
# Encode categorical variables
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [5]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [6]:
# One-hot encode 'Geography'
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [7]:
# Combine one-hot encoded columns with original data
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [8]:
# Split the data into features and target
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [9]:
## Split the data in training and tetsing sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [10]:
## Scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [11]:
# Save the encoders and scaler for later use
with open('label_encoder_gender1.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_geo1.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

with open('scaler1.pkl', 'wb') as file:
    pickle.dump(scaler, file)

#### ANN Regression Problem statement

In [12]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

2025-02-10 20:41:26.096931: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-02-10 20:41:26.135515: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-02-10 20:41:26.135597: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-02-10 20:41:26.136940: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-02-10 20:41:26.143372: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-02-10 20:41:26.862089: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

In [13]:
# Build the model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)  # Output layer for regression
])

## compile the model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [14]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

# Set up TensorBoard
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [15]:
# Set up Early Stopping
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [16]:
# Train the model
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorboard_callback]
)

Epoch 1/100
250/250 [==============================] - 1s 3ms/step - loss: 100369.1875 - mae: 100369.1875 - val_loss: 98492.3672 - val_mae: 98492.3672
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 99573.0625 - mae: 99573.0625 - val_loss: 96907.4609 - val_mae: 96907.4609
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 96846.3672 - mae: 96846.3672 - val_loss: 92925.0469 - val_mae: 92925.0469
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 91530.8984 - mae: 91530.8984 - val_loss: 86319.4531 - val_mae: 86319.4531
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 83829.7188 - mae: 83829.7188 - val_loss: 77838.4375 - val_mae: 77838.4375
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 74744.3750 - mae: 74744.3750 - val_loss: 68928.6250 - val_mae: 68928.6250
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 65929.5156 - mae: 65929.5156 - val_loss: 61208.2930 - val_mae: 61208.2930
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 58848.8164 - mae: 58848.8164 - val_loss: 55595.2461 - val_mae: 55595.2461
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 54221.1016 - mae: 54221.1016 - val_loss: 52456.0234 - val_mae: 52456.0234
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 51770.7031 - mae: 51770.7031 - val_loss: 51191.7422 - val_mae: 51191.7422
Epoch 11/100
250/250 [==============================] - 0s 1ms/step - loss: 50725.1641 - mae: 50725.1641 - val_loss: 50738.8398 - val_mae: 50738.8398
Epoch 12/100
250/250 [==============================] - 0s 1ms/step - loss: 50332.6719 - mae: 50332.6719 - val_loss: 50599.9531 - val_mae: 50599.9531
Epoch 13/100
250/250 [==============================] - 0s 1ms/step - loss: 50167.9453 - mae: 50167.9453 - val_loss: 50526.6328 - val_mae: 50526.6328
Epoch 14/100
250/250 [==============================] - 0s 1ms/step - loss: 50072.5234 - mae: 50072.5234 - val_loss: 50491.7578 - val_mae: 50491.7578
Epoch 15/100
250/250 [==============================] - 0s 1ms/step - loss: 50017.5898 - mae: 50017.5898 - val_loss: 50461.0273 - val_mae: 50461.0273
Epoch 16/100
250/250 [==============================] - 0s 1ms/step - loss: 49968.9570 - mae: 49968.9570 - val_loss: 50445.3906 - val_mae: 50445.3906
Epoch 17/100
250/250 [==============================] - 0s 1ms/step - loss: 49931.8438 - mae: 49931.8438 - val_loss: 50426.5586 - val_mae: 50426.5586
Epoch 18/100
250/250 [==============================] - 0s 1ms/step - loss: 49895.6523 - mae: 49895.6523 - val_loss: 50409.6680 - val_mae: 50409.6680
Epoch 19/100
250/250 [==============================] - 0s 1ms/step - loss: 49866.3945 - mae: 49866.3945 - val_loss: 50402.9922 - val_mae: 50402.9922
Epoch 20/100
250/250 [==============================] - 0s 1ms/step - loss: 49838.5078 - mae: 49838.5078 - val_loss: 50401.1367 - val_mae: 50401.1367
Epoch 21/100
250/250 [==============================] - 0s 1ms/step - loss: 49809.4062 - mae: 49809.4062 - val_loss: 50376.9141 - val_mae: 50376.9141
Epoch 22/100
250/250 [==============================] - 0s 1ms/step - loss: 49788.9336 - mae: 49788.9336 - val_loss: 50363.6016 - val_mae: 50363.6016
Epoch 23/100
250/250 [==============================] - 0s 1ms/step - loss: 49768.1875 - mae: 49768.1875 - val_loss: 50354.3945 - val_mae: 50354.3945
Epoch 24/100
250/250 [==============================] - 0s 1ms/step - loss: 49744.1133 - mae: 49744.1133 - val_loss: 50352.9336 - val_mae: 50352.9336
Epoch 25/100
250/250 [==============================] - 0s 1ms/step - loss: 49729.7070 - mae: 49729.7070 - val_loss: 50352.2852 - val_mae: 50352.2852
Epoch 26/100
250/250 [==============================] - 0s 2ms/step - loss: 49709.2266 - mae: 49709.2266 - val_loss: 50342.7773 - val_mae: 50342.7773
Epoch 27/100
250/250 [==============================] - 0s 1ms/step - loss: 49693.7266 - mae: 49693.7266 - val_loss: 50336.0742 - val_mae: 50336.0742
Epoch 28/100
250/250 [==============================] - 0s 1ms/step - loss: 49676.8672 - mae: 49676.8672 - val_loss: 50338.4688 - val_mae: 50338.4688
Epoch 29/100
250/250 [==============================] - 0s 1ms/step - loss: 49664.3242 - mae: 49664.3242 - val_loss: 50337.3711 - val_mae: 50337.3711
Epoch 30/100
250/250 [==============================] - 0s 1ms/step - loss: 49649.7578 - mae: 49649.7578 - val_loss: 50329.4414 - val_mae: 50329.4414
Epoch 31/100
250/250 [==============================] - 0s 1ms/step - loss: 49638.4922 - mae: 49638.4922 - val_loss: 50315.8047 - val_mae: 50315.8047
Epoch 32/100
250/250 [==============================] - 0s 1ms/step - loss: 49626.1992 - mae: 49626.1992 - val_loss: 50316.0781 - val_mae: 50316.0781
Epoch 33/100
250/250 [==============================] - 0s 1ms/step - loss: 49617.7070 - mae: 49617.7070 - val_loss: 50316.7656 - val_mae: 50316.7656
Epoch 34/100
250/250 [==============================] - 0s 2ms/step - loss: 49605.7734 - mae: 49605.7734 - val_loss: 50307.3750 - val_mae: 50307.3750
Epoch 35/100
250/250 [==============================] - 0s 1ms/step - loss: 49598.1211 - mae: 49598.1211 - val_loss: 50313.7109 - val_mae: 50313.7109
Epoch 36/100
250/250 [==============================] - 0s 1ms/step - loss: 49584.1719 - mae: 49584.1719 - val_loss: 50302.9297 - val_mae: 50302.9297
Epoch 37/100
250/250 [==============================] - 0s 1ms/step - loss: 49574.4219 - mae: 49574.4219 - val_loss: 50301.7109 - val_mae: 50301.7109
Epoch 38/100
250/250 [==============================] - 0s 1ms/step - loss: 49566.8008 - mae: 49566.8008 - val_loss: 50300.2969 - val_mae: 50300.2969
Epoch 39/100
250/250 [==============================] - 0s 1ms/step - loss: 49559.5312 - mae: 49559.5312 - val_loss: 50309.2539 - val_mae: 50309.2539
Epoch 40/100
250/250 [==============================] - 0s 1ms/step - loss: 49550.3711 - mae: 49550.3711 - val_loss: 50308.0547 - val_mae: 50308.0547
Epoch 41/100
250/250 [==============================] - 0s 2ms/step - loss: 49539.9219 - mae: 49539.9219 - val_loss: 50305.9023 - val_mae: 50305.9023
Epoch 42/100
250/250 [==============================] - 0s 1ms/step - loss: 49534.3906 - mae: 49534.3906 - val_loss: 50309.2266 - val_mae: 50309.2266
Epoch 43/100
250/250 [==============================] - 0s 1ms/step - loss: 49526.5742 - mae: 49526.5742 - val_loss: 50318.5273 - val_mae: 50318.5273
Epoch 44/100
250/250 [==============================] - 0s 1ms/step - loss: 49519.0391 - mae: 49519.0391 - val_loss: 50312.5117 - val_mae: 50312.5117
Epoch 45/100
250/250 [==============================] - 0s 1ms/step - loss: 49513.2578 - mae: 49513.2578 - val_loss: 50311.6016 - val_mae: 50311.6016
Epoch 46/100
250/250 [==============================] - 0s 1ms/step - loss: 49506.8672 - mae: 49506.8672 - val_loss: 50316.2461 - val_mae: 50316.2461
Epoch 47/100
250/250 [==============================] - 0s 1ms/step - loss: 49498.1797 - mae: 49498.1797 - val_loss: 50323.9414 - val_mae: 50323.9414
Epoch 48/100
250/250 [==============================] - 0s 2ms/step - loss: 49492.4102 - mae: 49492.4102 - val_loss: 50317.6406 - val_mae: 50317.6406

In [17]:
%load_ext tensorboard

In [18]:
%tensorboard --logdir regressionlogs/fit

In [21]:
!kill 31212

/bin/bash: line 0: kill: (31212) - No such process

In [ ]:
## Evaluate model on the test data
test_loss,test_mae=model.evaluate(X_test,y_test)
print(f'Test MAE : {test_mae}') # closer to zero its good

63/63 [==============================] - 0s 813us/step - loss: 50300.2969 - mae: 50300.2969
Test MAE : 50300.296875

In [20]:
model.save('regression_model.h5')

/home/npci-admin/anaconda3/lib/python3.9/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(